Ted 2.15

diff --git a/appFrame/configure b/appFrame/configure
--- a/appFrame/configure
+++ b/appFrame/configure
@@ -2982,9 +2982,6 @@ fi
     XPM_SHARED_REF=
 
     XPM_FOUND=0
-    cat >>confdefs.h <<\EOF
-#define XPM_FOUND 0
-EOF
 
     ac_xpm_includes=${ac_xpm_includes:-NO}
     ac_xpm_libraries=${ac_xpm_libraries:-NO}
@@ -3041,6 +3038,14 @@ EOF
 		break
 	    fi
 
+	if  test -r "$ac_dir/libXpm.dylib"
+	    then
+		ac_xpm_libraries=$ac_dir
+		ac_xpm_shared_lib=$ac_dir/libXpm.dylib
+		found=yes
+		break
+	    fi
+
 	if  test $found = yes
 	    then
 		break
@@ -3052,8 +3057,14 @@ EOF
     #echo Includes : $ac_xpm_includes
     #echo Libraries: $ac_xpm_libraries
 
-    if  test $ac_xpm_includes != NO
+    if  test $ac_xpm_includes = NO
     then
+	XPM_FOUND=0
+	cat >>confdefs.h <<\EOF
+#define XPM_FOUND 0
+EOF
+
+    else
 	XPM_FOUND=1
 	cat >>confdefs.h <<\EOF
 #define XPM_FOUND 1
@@ -3157,6 +3168,13 @@ EOF
 		found=yes
 	    fi
 
+	if  test -r "$ac_dir/libXm.dylib"
+	    then
+		ac_xm_libraries=$ac_dir
+		ac_xm_shared_lib=$ac_dir/libXm.dylib
+		found=yes
+	    fi
+
 	if  test $found = yes
 	    then
 		break
@@ -3169,7 +3187,7 @@ EOF
 
     if  test $ac_xm_includes != NO
     then
-	XM_CFLAGS=-I$ac_xm_includes
+	XM_CFLAGS=" -I$ac_xm_includes"
 	MOTIF_HEADERS_FOUND=YES
 
 	if  test "$XM_CFLAGS" = "$X_CFLAGS"
@@ -3180,7 +3198,7 @@ EOF
 
     if  test $ac_xm_libraries != NO
     then
-	XM_LIBS="-L$ac_xm_libraries"
+	XM_LIBS=" -L$ac_xm_libraries"
 	MOTIF_LIBS_FOUND=YES
 
 	if  test "$XM_LIBS" = "$X_LIBS"
@@ -3234,15 +3252,40 @@ EOF
 	XM_STATIC_REF="$XM_LIBS -lXm"
     fi
 
+    #  Hack to cope with the linker on some BSD operating systems
+    #  I do not think that this hack will be acceptable on the long
+    #  term.
+    #  *   The hack is in the wrong position: It is in the Motif
+    #      configuration, whereas it should be in some more generic
+    #      environment.
+    #  *   It bypasses the generic autoconf framework. This might
+    #      pose more issues than it removes.
+    #
+
+    if  test $ac_xm_libraries != NO
+    then
+	if  uname -s > /dev/null
+	then
+	    ac_os_xm=`uname -s`
+	    case $ac_os_xm in
+		FreeBsd|NetBsd|OpenBsd)
+		    XM_EXTRA_LIBS="$XM_EXTRA_LIBS -Wl,-R$ac_xm_libraries"
+		    ;;
+		*)
+		    ;;
+	    esac
+	fi
+    fi
+
     XM_SHARED_REF="$XM_LIBS -lXm"
 
-echo "$as_me:3239: checking for ANSI C header files" >&5
+echo "$as_me:3282: checking for ANSI C header files" >&5
 echo $ECHO_N "checking for ANSI C header files... $ECHO_C" >&6
 if test "${ac_cv_header_stdc+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   cat >conftest.$ac_ext <<_ACEOF
-#line 3245 "configure"
+#line 3288 "configure"
 #include "confdefs.h"
 #include <stdlib.h>
 #include <stdarg.h>
@@ -3250,13 +3293,13 @@ else
 #include <float.h>
 
 _ACEOF
-if { (eval echo "$as_me:3253: \"$ac_cpp conftest.$ac_ext\"") >&5
+if { (eval echo "$as_me:3296: \"$ac_cpp conftest.$ac_ext\"") >&5
   (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
   ac_status=$?
   egrep -v '^ *\+' conftest.er1 >conftest.err
   rm -f conftest.er1
   cat conftest.err >&5
-  echo "$as_me:3259: \$? = $ac_status" >&5
+  echo "$as_me:3302: \$? = $ac_status" >&5
   (exit $ac_status); } >/dev/null; then
   if test -s conftest.err; then
     ac_cpp_err=$ac_c_preproc_warn_flag
@@ -3278,7 +3321,7 @@ rm -f conftest.err conftest.$ac_ext
 if test $ac_cv_header_stdc = yes; then
   # SunOS 4.x string.h does not declare mem*, contrary to ANSI.
   cat >conftest.$ac_ext <<_ACEOF
-#line 3281 "configure"
+#line 3324 "configure"
 #include "confdefs.h"
 #include <string.h>
 
@@ -3296,7 +3339,7 @@ fi
 if test $ac_cv_header_stdc = yes; then
   # ISC 2.0.2 stdlib.h does not declare free, contrary to ANSI.
   cat >conftest.$ac_ext <<_ACEOF
-#line 3299 "configure"
+#line 3342 "configure"
 #include "confdefs.h"
 #include <stdlib.h>
 
@@ -3317,7 +3360,7 @@ if test $ac_cv_header_stdc = yes; then
   :
 else
   cat >conftest.$ac_ext <<_ACEOF
-#line 3320 "configure"
+#line 3363 "configure"
 #include "confdefs.h"
 #include <ctype.h>
 #if ((' ' & 0x0FF) == 0x020)
@@ -3343,15 +3386,15 @@ main ()
 }
 _ACEOF
 rm -f conftest$ac_exeext
-if { (eval echo "$as_me:3346: \"$ac_link\"") >&5
+if { (eval echo "$as_me:3389: \"$ac_link\"") >&5
   (eval $ac_link) 2>&5
   ac_status=$?
-  echo "$as_me:3349: \$? = $ac_status" >&5
+  echo "$as_me:3392: \$? = $ac_status" >&5
   (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
-  { (eval echo "$as_me:3351: \"$ac_try\"") >&5
+  { (eval echo "$as_me:3394: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
-  echo "$as_me:3354: \$? = $ac_status" >&5
+  echo "$as_me:3397: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
   :
 else
@@ -3364,7 +3407,7 @@ rm -f core core.* *.core conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
 fi
 fi
 fi
-echo "$as_me:3367: result: $ac_cv_header_stdc" >&5
+echo "$as_me:3410: result: $ac_cv_header_stdc" >&5
 echo "${ECHO_T}$ac_cv_header_stdc" >&6
 if test $ac_cv_header_stdc = yes; then
 
@@ -3377,23 +3420,23 @@ fi
 for ac_header in fcntl.h sys/time.h unistd.h
 do
 as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
-echo "$as_me:3380: checking for $ac_header" >&5
+echo "$as_me:3423: checking for $ac_header" >&5
 echo $ECHO_N "checking for $ac_header... $ECHO_C" >&6
 if eval "test \"\${$as_ac_Header+set}\" = set"; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   cat >conftest.$ac_ext <<_ACEOF
-#line 3386 "configure"
+#line 3429 "configure"
 #include "confdefs.h"
 #include <$ac_header>
 _ACEOF
-if { (eval echo "$as_me:3390: \"$ac_cpp conftest.$ac_ext\"") >&5
+if { (eval echo "$as_me:3433: \"$ac_cpp conftest.$ac_ext\"") >&5
   (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
   ac_status=$?
   egrep -v '^ *\+' conftest.er1 >conftest.err
   rm -f conftest.er1
   cat conftest.err >&5
-  echo "$as_me:3396: \$? = $ac_status" >&5
+  echo "$as_me:3439: \$? = $ac_status" >&5
   (exit $ac_status); } >/dev/null; then
   if test -s conftest.err; then
     ac_cpp_err=$ac_c_preproc_warn_flag
@@ -3412,7 +3455,7 @@ else
 fi
 rm -f conftest.err conftest.$ac_ext
 fi
-echo "$as_me:3415: result: `eval echo '${'$as_ac_Header'}'`" >&5
+echo "$as_me:3458: result: `eval echo '${'$as_ac_Header'}'`" >&5
 echo "${ECHO_T}`eval echo '${'$as_ac_Header'}'`" >&6
 if test `eval echo '${'$as_ac_Header'}'` = yes; then
   cat >>confdefs.h <<EOF
@@ -3422,7 +3465,7 @@ EOF
 fi
 done
 
-echo "$as_me:3425: checking for $CC option to accept ANSI C" >&5
+echo "$as_me:3468: checking for $CC option to accept ANSI C" >&5
 echo $ECHO_N "checking for $CC option to accept ANSI C... $ECHO_C" >&6
 if test "${ac_cv_prog_cc_stdc+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -3430,7 +3473,7 @@ else
   ac_cv_prog_cc_stdc=no
 ac_save_CC=$CC
 cat >conftest.$ac_ext <<_ACEOF
-#line 3433 "configure"
+#line 3476 "configure"
 #include "confdefs.h"
 #include <stdarg.h>
 #include <stdio.h>
@@ -3479,16 +3522,16 @@ for ac_arg in "" -qlanglvl=ansi -std1 -Ae "-Aa -D_HPUX_SOURCE" "-Xc -D__EXTENSIO
 do
   CC="$ac_save_CC $ac_arg"
   rm -f conftest.$ac_objext
-if { (eval echo "$as_me:3482: \"$ac_compile\"") >&5
+if { (eval echo "$as_me:3525: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
-  echo "$as_me:3485: \$? = $ac_status" >&5
+  echo "$as_me:3528: \$? = $ac_status" >&5
   (exit $ac_status); } &&
          { ac_try='test -s conftest.$ac_objext'
-  { (eval echo "$as_me:3488: \"$ac_try\"") >&5
+  { (eval echo "$as_me:3531: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
-  echo "$as_me:3491: \$? = $ac_status" >&5
+  echo "$as_me:3534: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
   ac_cv_prog_cc_stdc=$ac_arg
 break
@@ -3505,21 +3548,21 @@ fi
 
 case "x$ac_cv_prog_cc_stdc" in
   x|xno)
-    echo "$as_me:3508: result: none needed" >&5
+    echo "$as_me:3551: result: none needed" >&5
 echo "${ECHO_T}none needed" >&6 ;;
   *)
-    echo "$as_me:3511: result: $ac_cv_prog_cc_stdc" >&5
+    echo "$as_me:3554: result: $ac_cv_prog_cc_stdc" >&5
 echo "${ECHO_T}$ac_cv_prog_cc_stdc" >&6
     CC="$CC $ac_cv_prog_cc_stdc" ;;
 esac
 
-echo "$as_me:3516: checking for an ANSI C-conforming const" >&5
+echo "$as_me:3559: checking for an ANSI C-conforming const" >&5
 echo $ECHO_N "checking for an ANSI C-conforming const... $ECHO_C" >&6
 if test "${ac_cv_c_const+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   cat >conftest.$ac_ext <<_ACEOF
-#line 3522 "configure"
+#line 3565 "configure"
 #include "confdefs.h"
 
 int
@@ -3577,16 +3620,16 @@ main ()
 }
 _ACEOF
 rm -f conftest.$ac_objext
-if { (eval echo "$as_me:3580: \"$ac_compile\"") >&5
+if { (eval echo "$as_me:3623: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
-  echo "$as_me:3583: \$? = $ac_status" >&5
+  echo "$as_me:3626: \$? = $ac_status" >&5
   (exit $ac_status); } &&
          { ac_try='test -s conftest.$ac_objext'
-  { (eval echo "$as_me:3586: \"$ac_try\"") >&5
+  { (eval echo "$as_me:3629: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
-  echo "$as_me:3589: \$? = $ac_status" >&5
+  echo "$as_me:3632: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
   ac_cv_c_const=yes
 else
@@ -3596,7 +3639,7 @@ ac_cv_c_const=no
 fi
 rm -f conftest.$ac_objext conftest.$ac_ext
 fi
-echo "$as_me:3599: result: $ac_cv_c_const" >&5
+echo "$as_me:3642: result: $ac_cv_c_const" >&5
 echo "${ECHO_T}$ac_cv_c_const" >&6
 if test $ac_cv_c_const = no; then
 
@@ -3606,7 +3649,7 @@ EOF
 
 fi
 
-echo "$as_me:3609: checking whether byte ordering is bigendian" >&5
+echo "$as_me:3652: checking whether byte ordering is bigendian" >&5
 echo $ECHO_N "checking whether byte ordering is bigendian... $ECHO_C" >&6
 if test "${ac_cv_c_bigendian+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -3614,7 +3657,7 @@ else
   ac_cv_c_bigendian=unknown
 # See if sys/param.h defines the BYTE_ORDER macro.
 cat >conftest.$ac_ext <<_ACEOF
-#line 3617 "configure"
+#line 3660 "configure"
 #include "confdefs.h"
 #include <sys/types.h>
 #include <sys/param.h>
@@ -3631,20 +3674,20 @@ main ()
 }
 _ACEOF
 rm -f conftest.$ac_objext
-if { (eval echo "$as_me:3634: \"$ac_compile\"") >&5
+if { (eval echo "$as_me:3677: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
-  echo "$as_me:3637: \$? = $ac_status" >&5
+  echo "$as_me:3680: \$? = $ac_status" >&5
   (exit $ac_status); } &&
          { ac_try='test -s conftest.$ac_objext'
-  { (eval echo "$as_me:3640: \"$ac_try\"") >&5
+  { (eval echo "$as_me:3683: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
-  echo "$as_me:3643: \$? = $ac_status" >&5
+  echo "$as_me:3686: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
   # It does; now see whether it defined to BIG_ENDIAN or not.
 cat >conftest.$ac_ext <<_ACEOF
-#line 3647 "configure"
+#line 3690 "configure"
 #include "confdefs.h"
 #include <sys/types.h>
 #include <sys/param.h>
@@ -3661,16 +3704,16 @@ main ()
 }
 _ACEOF
 rm -f conftest.$ac_objext
-if { (eval echo "$as_me:3664: \"$ac_compile\"") >&5
+if { (eval echo "$as_me:3707: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
-  echo "$as_me:3667: \$? = $ac_status" >&5
+  echo "$as_me:3710: \$? = $ac_status" >&5
   (exit $ac_status); } &&
          { ac_try='test -s conftest.$ac_objext'
-  { (eval echo "$as_me:3670: \"$ac_try\"") >&5
+  { (eval echo "$as_me:3713: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
-  echo "$as_me:3673: \$? = $ac_status" >&5
+  echo "$as_me:3716: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
   ac_cv_c_bigendian=yes
 else
@@ -3686,12 +3729,12 @@ fi
 rm -f conftest.$ac_objext conftest.$ac_ext
 if test $ac_cv_c_bigendian = unknown; then
 if test "$cross_compiling" = yes; then
-  { { echo "$as_me:3689: error: cannot run test program while cross compiling" >&5
+  { { echo "$as_me:3732: error: cannot run test program while cross compiling" >&5
 echo "$as_me: error: cannot run test program while cross compiling" >&2;}
    { (exit 1); exit 1; }; }
 else
   cat >conftest.$ac_ext <<_ACEOF
-#line 3694 "configure"
+#line 3737 "configure"
 #include "confdefs.h"
 int
 main ()
@@ -3707,15 +3750,15 @@ main ()
 }
 _ACEOF
 rm -f conftest$ac_exeext
-if { (eval echo "$as_me:3710: \"$ac_link\"") >&5
+if { (eval echo "$as_me:3753: \"$ac_link\"") >&5
   (eval $ac_link) 2>&5
   ac_status=$?
-  echo "$as_me:3713: \$? = $ac_status" >&5
+  echo "$as_me:3756: \$? = $ac_status" >&5
   (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
-  { (eval echo "$as_me:3715: \"$ac_try\"") >&5
+  { (eval echo "$as_me:3758: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
-  echo "$as_me:3718: \$? = $ac_status" >&5
+  echo "$as_me:3761: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
   ac_cv_c_bigendian=no
 else
@@ -3728,7 +3771,7 @@ rm -f core core.* *.core conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
 fi
 fi
 fi
-echo "$as_me:3731: result: $ac_cv_c_bigendian" >&5
+echo "$as_me:3774: result: $ac_cv_c_bigendian" >&5
 echo "${ECHO_T}$ac_cv_c_bigendian" >&6
 if test $ac_cv_c_bigendian = yes; then
 
@@ -3746,28 +3789,42 @@ fi
     GTK_HEADERS_FOUND=NO
     GTK_LIBS_FOUND=NO
 
-    if  ( gtk-config --cflags ) > /dev/null
+    # gtk 1.*
+    if  ( gtk-config --cflags ) > /dev/null 2>&1
     then
 	GTK_CFLAGS=`gtk-config --cflags`
 	GTK_HEADERS_FOUND=YES
     fi
 
-    if  ( gtk-config --libs ) > /dev/null
+    if  ( gtk-config --libs ) > /dev/null 2>&1
     then
 	GTK_LIBS=`gtk-config --libs`
+	GTK_LIBS_FOUND=YES
+    fi
+
+    # gtk 2.0
+    if  ( pkg-config --cflags gtk+-2.0 ) > /dev/null 2>&1
+    then
+	GTK_CFLAGS=`pkg-config --cflags gtk+-2.0`
+	GTK_HEADERS_FOUND=YES
+    fi
+
+    if  ( pkg-config --libs gtk+-2.0 ) > /dev/null 2>&1
+    then
+	GTK_LIBS=`pkg-config --libs gtk+-2.0`
 	GTK_LIBS_FOUND=YES
     fi
 
 for ac_func in socket strerror uname mkstemp
 do
 as_ac_var=`echo "ac_cv_func_$ac_func" | $as_tr_sh`
-echo "$as_me:3764: checking for $ac_func" >&5
+echo "$as_me:3821: checking for $ac_func" >&5
 echo $ECHO_N "checking for $ac_func... $ECHO_C" >&6
 if eval "test \"\${$as_ac_var+set}\" = set"; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   cat >conftest.$ac_ext <<_ACEOF
-#line 3770 "configure"
+#line 3827 "configure"
 #include "confdefs.h"
 /* System header to define __stub macros and hopefully few prototypes,
     which can conflict with char $ac_func (); below.  */
@@ -3798,16 +3855,16 @@ f = $ac_func;
 }
 _ACEOF
 rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:3801: \"$ac_link\"") >&5
+if { (eval echo "$as_me:3858: \"$ac_link\"") >&5
   (eval $ac_link) 2>&5
   ac_status=$?
-  echo "$as_me:3804: \$? = $ac_status" >&5
+  echo "$as_me:3861: \$? = $ac_status" >&5
   (exit $ac_status); } &&
          { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:3807: \"$ac_try\"") >&5
+  { (eval echo "$as_me:3864: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
-  echo "$as_me:3810: \$? = $ac_status" >&5
+  echo "$as_me:3867: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
   eval "$as_ac_var=yes"
 else
@@ -3817,7 +3874,7 @@ eval "$as_ac_var=no"
 fi
 rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
 fi
-echo "$as_me:3820: result: `eval echo '${'$as_ac_var'}'`" >&5
+echo "$as_me:3877: result: `eval echo '${'$as_ac_var'}'`" >&5
 echo "${ECHO_T}`eval echo '${'$as_ac_var'}'`" >&6
 if test `eval echo '${'$as_ac_var'}'` = yes; then
   cat >>confdefs.h <<EOF
@@ -4068,7 +4125,7 @@ DEFS=-DHAVE_CONFIG_H
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:4071: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:4128: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -4240,7 +4297,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:4243: error: ambiguous option: $1
+    { { echo "$as_me:4300: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -4259,7 +4316,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:4262: error: unrecognized option: $1
+  -*) { { echo "$as_me:4319: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -4296,7 +4353,7 @@ do
   # Handling of arguments.
   "makefile" ) CONFIG_FILES="$CONFIG_FILES makefile" ;;
   "appFrameConfig.h" ) CONFIG_HEADERS="$CONFIG_HEADERS appFrameConfig.h" ;;
-  *) { { echo "$as_me:4299: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:4356: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -4516,7 +4573,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:4519: creating $ac_file" >&5
+    { echo "$as_me:4576: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -4534,7 +4591,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:4537: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:4594: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -4547,7 +4604,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:4550: error: cannot find input file: $f" >&5
+           { { echo "$as_me:4607: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -4607,7 +4664,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:4610: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:4667: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -4618,7 +4675,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:4621: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:4678: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -4631,7 +4688,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:4634: error: cannot find input file: $f" >&5
+           { { echo "$as_me:4691: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -4748,7 +4805,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:4751: $ac_file is unchanged" >&5
+      { echo "$as_me:4808: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
diff --git a/tedPackage/configure b/tedPackage/configure
--- a/tedPackage/configure
+++ b/tedPackage/configure
@@ -939,27 +939,83 @@ EOF
 #define BINDIR $BINDIR
 EOF
 
-M_SYSTEM=`uname -s | tr :/ __`
-M_MACHINE=`uname -m | tr :/ __`
+M_SYSTEM=`uname -s  | tr ':/ ' ___`
+M_MACHINE=`uname -m | tr ':/ ' ___`
 
-case $M_SYSTEM in
-    OpenBSD|FreeBSD|NetBSD)
-	M_CHOWN_ARG=root:wheel
-	;;
-    *)
-	if  `id -u` = 0
-	then
-	    if  id -gn > /dev/null
+M_PKG_OWNER=NO
+M_PKG_GROUP=NO
+
+########################################################################
+
+if  ls -l /bin/ls > $$-scratch
+then
+    read modes links owner group size month day year_time name < $$-scratch
+
+    if  test $name = "/bin/ls"
+    then
+	M_PKG_OWNER=$owner
+	M_PKG_GROUP=$group
+	M_CHOWN_ARG=$M_PKG_OWNER:$M_PKG_GROUP
+    fi
+fi
+
+rm -f $$-scratch
+
+########################################################################
+
+if  test $M_PKG_OWNER = NO
+then
+    case $M_SYSTEM in
+	OpenBSD|FreeBSD|NetBSD|Darwin)
+	    M_PKG_OWNER=root
+	    M_PKG_GROUP=wheel
+	    M_CHOWN_ARG=root:wheel
+	    ;;
+	*)
+	    if  test `id -u` = 0
 	    then
-		M_CHOWN_ARG=root:`id -gn`
+		if  id -gn > /dev/null
+		then
+		    M_PKG_GROUP=`id -gn`
+		else
+		    M_PKG_GROUP=root
+		fi
+		M_PKG_OWNER=root
+		M_CHOWN_ARG=$M_PKG_OWNER:$M_PKG_GROUP
 	    else
+		M_PKG_OWNER=root
+		M_PKG_GROUP=root
 		M_CHOWN_ARG=root:root
 	    fi
-	else
-	    M_CHOWN_ARG=root:root
-	fi
-	;;
-esac
+	    ;;
+    esac
+fi
+
+########################################################################
+
+if  tar cf scratch.tar \
+           --owner=$M_PKG_OWNER --group=$M_PKG_GROUP configure 2>/dev/null
+then
+    TAR_CHOWN_ARGS="--owner=$M_PKG_OWNER --group=$M_PKG_GROUP"
+    rm -f scratch.tar
+
+    CHECK_ID_CMD=": ok"
+    CHOWN_CMD=":"
+else
+    TAR_CHOWN_ARGS=""
+    CHECK_ID_CMD='@( test `id -u` = 0 || ( echo YOU MUST BE ROOT && false ) )'
+    CHOWN_CMD="chown $M_CHOWN_ARG"
+fi
+
+########################################################################
+
+if  test x_$RPM_BUILD_ROOT != x_
+then
+    CHECK_ID_CMD=": ok"
+    CHOWN_CMD=":"
+fi
+
+########################################################################
 
 ########################################################################
 
@@ -1073,7 +1129,7 @@ rm -f confdef2opt.sed
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:1076: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:1132: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -1240,7 +1296,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:1243: error: ambiguous option: $1
+    { { echo "$as_me:1299: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -1259,7 +1315,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:1262: error: unrecognized option: $1
+  -*) { { echo "$as_me:1318: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -1295,7 +1351,7 @@ do
   case "$ac_config_target" in
   # Handling of arguments.
   "makefile" ) CONFIG_FILES="$CONFIG_FILES makefile" ;;
-  *) { { echo "$as_me:1298: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:1354: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -1380,7 +1436,12 @@ s,@EXEC_PREFIX@,$EXEC_PREFIX,;t t
 s,@BINDIR@,$BINDIR,;t t
 s,@M_SYSTEM@,$M_SYSTEM,;t t
 s,@M_MACHINE@,$M_MACHINE,;t t
+s,@M_PKG_OWNER@,$M_PKG_OWNER,;t t
+s,@M_PKG_GROUP@,$M_PKG_GROUP,;t t
 s,@M_CHOWN_ARG@,$M_CHOWN_ARG,;t t
+s,@TAR_CHOWN_ARGS@,$TAR_CHOWN_ARGS,;t t
+s,@CHECK_ID_CMD@,$CHECK_ID_CMD,;t t
+s,@CHOWN_CMD@,$CHOWN_CMD,;t t
 CEOF
 
 EOF
@@ -1490,7 +1551,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:1493: creating $ac_file" >&5
+    { echo "$as_me:1554: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -1508,7 +1569,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:1511: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:1572: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -1521,7 +1582,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:1524: error: cannot find input file: $f" >&5
+           { { echo "$as_me:1585: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
